@host = localhost
@port = 3000
@apiversion = api/v1

### Registrar Um Novo Usuário
POST http://{{host}}:{{port}}/{{apiversion}}/usuarios
Content-type: application/json

{
    "nome":"Walber",
    "email":"walber@mail.com",
    "senha":"123456",
    "tipo": "ADMINISTRADOR"
}

### Autenticar Um Usuário Existente a Partir das Credenciais
POST http://{{host}}:{{port}}/{{apiversion}}/usuarios/autenticacao
Content-type: application/json

{
    "email":"walber@mail.com",
    "senha":"123456"
}