@host = localhost
@port = 3000
@apiversion = api/v1

### Recuperar Um Categoria por ID
GET http://{{host}}:{{port}}/{{apiversion}}/categorias/26569beb-ddf9-4100-b40b-933f0a255fea

### Recuperar Todas as Categorias
GET http://{{host}}:{{port}}/{{apiversion}}/categorias

### Inserir Uma Categoria
POST http://{{host}}:{{port}}/{{apiversion}}/categorias
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE0MTI3OTJmLWRkNjUtNDc4MS1hZTQzLWI3MmJkNjQ3MGRlNiIsIm5vbWUiOiJXYWxiZXIiLCJlbWFpbCI6IndhbGJlckBtYWlsLmNvbSIsInRpcG8iOiJBRE1JTklTVFJBRE9SIiwiaWF0IjoxNzA0ODQ2NzAwLCJleHAiOjE3MDQ4NTAzMDB9.h7DLcnW3lS7f0IeuKaC9MNs55W9DgBIoMskSYYkK3wg

{
    "nome":"Sala de jantar"
}

### Atualizar Categoria

PUT http://{{host}}:{{port}}/{{apiversion}}/categorias/26569beb-ddf9-4100-b40b-933f0a255fef
Content-Type: application/json

{
    "id": "26569beb-ddf9-4100-b40b-933f0a255fef",
    "nome": "Sala"
}

### Deletar Categoria

DELETE http://{{host}}:{{port}}/{{apiversion}}/categorias/0309cb21-cc68-47ba-b2fa-ca39bdb835de

